converter:
  enabled: true
  inputDirectory: "plugins/CIT-paper/packs"
  outputDirectory: "plugins/CIT-paper/converted-packs"
  clearOutputDirectory: true
  clearConfigs: true
  preserveCitDirectories: true
