# MODERN is recommended for 1.21.2+
# ORAXEN only works with Oraxen and may work on older versions
mode: MODERN

# enable for debugging
verboseLogging: false

# if empty, system-provided temporary folder will be used
tempFolder: ""

converter:
  # whether to run converter on each start
  enabled: true
  # directory where you should put your resource packs
  inputDirectory: "plugins/CIT-paper/packs"
  # directory where converted resource packs will go
  outputDirectory: "plugins/CIT-paper/converted-packs"
  # clear rename lists before every conversion
  clearConfigs: true
  # preserve assets/minecraft/optifine/cit folders in converted resource packs
  preserveCitDirectories: false
  # merge all packs into one
  mergePacks: false
  # if this is not empty, output merged pack as one file
  mergedOutputFile: ""
