name: CIT-paper
version: '1.4.3'
main: org.vinerdream.citPaper.CITPaper
api-version: '1.21'
commands:
  cit-paper:
    description: Reload config/regenerate resource packs
    usage: /cit-paper <reload|regenerate>
    permission: cit-paper.command
